import React from 'react';
import { Download, CheckCircle, Clock, AlertCircle, Loader2 } from 'lucide-react';

export type ReportStatus = 'ready' | 'generating' | 'failed' | 'scheduled';

export interface ReportRow {
  id: string;
  name: string;
  category: string;
  generatedBy: string;
  date: string;
  status: ReportStatus;
  size?: string;
}

const STATUS_CONFIG: Record<ReportStatus, { label: string; icon: React.FC<{ className?: string }>; color: string }> = {
  ready:      { label: 'Ready',      icon: CheckCircle, color: 'text-emerald-400' },
  generating: { label: 'Generating', icon: Loader2,     color: 'text-sky-400' },
  failed:     { label: 'Failed',     icon: AlertCircle, color: 'text-red-400' },
  scheduled:  { label: 'Scheduled',  icon: Clock,       color: 'text-amber-400' },
};

interface ReportTableProps {
  rows: ReportRow[];
  onExport?: (id: string) => void;
}

export const ReportTable: React.FC<ReportTableProps> = ({ rows, onExport }) => (
  <div className="bg-[#1E293B] border border-[#334155] rounded-2xl overflow-hidden">
    {/* Header */}
    <div className="px-5 py-3 grid grid-cols-12 text-[10px] text-slate-500 uppercase tracking-widest border-b border-[#334155]">
      <span className="col-span-4">Name</span>
      <span className="col-span-2">Category</span>
      <span className="col-span-2">Generated By</span>
      <span className="col-span-2">Date</span>
      <span className="col-span-1 text-center">Status</span>
      <span className="col-span-1 text-right">Export</span>
    </div>

    {/* Rows */}
    <div className="divide-y divide-[#334155]">
      {rows.map((row) => {
        const sc = STATUS_CONFIG[row.status];
        const StatusIcon = sc.icon;
        return (
          <div
            key={row.id}
            className="px-5 py-3.5 grid grid-cols-12 items-center hover:bg-slate-800/30 transition-colors"
          >
            <div className="col-span-4">
              <p className="text-sm font-medium text-slate-200 truncate">{row.name}</p>
              {row.size && <p className="text-[10px] text-slate-600">{row.size}</p>}
            </div>
            <span className="col-span-2 text-xs text-slate-400">{row.category}</span>
            <span className="col-span-2 text-xs text-slate-400 truncate">{row.generatedBy}</span>
            <span className="col-span-2 text-xs text-slate-500">{row.date}</span>
            <div className={`col-span-1 flex items-center justify-center gap-1 text-[10px] font-medium ${sc.color}`}>
              <StatusIcon className={`w-3 h-3 ${row.status === 'generating' ? 'animate-spin' : ''}`} />
            </div>
            <div className="col-span-1 flex justify-end">
              {row.status === 'ready' && (
                <button
                  onClick={() => onExport?.(row.id)}
                  aria-label={`Export ${row.name}`}
                  className="w-7 h-7 flex items-center justify-center rounded-lg text-slate-500 hover:text-emerald-400 hover:bg-emerald-500/10 transition-colors"
                >
                  <Download className="w-3.5 h-3.5" />
                </button>
              )}
            </div>
          </div>
        );
      })}
    </div>
  </div>
);
